language: php

before_install:
  - travis_retry composer self-update
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

install: composer update --prefer-source --no-interaction --dev

script: composer test

matrix:
  include:
    - php: 7.0
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.7.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.7.*
